/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=fixtures/qualification/wrangler.jsonc --include-runtime=false --env-interface=QualificationEnv fixtures/qualification/worker-configuration.d.ts` (hash: 8a6532fe19dc09fe6f62527fa1193204)
interface __BaseEnv_QualificationEnv {
	KV: KVNamespace;
	BUCKET: R2Bucket;
	DB: D1Database;
	QUEUE: Queue;
	LOADER: WorkerLoader;
	PROBE: DurableObjectNamespace<import("./worker").Recovery>;
	SERVICE: Service<typeof import("./worker").ServiceProbe>;
	FLOW: Workflow<Parameters<import("./worker").RecoveryWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "Recovery";
	}
	interface Env extends __BaseEnv_QualificationEnv {}
}
interface QualificationEnv extends __BaseEnv_QualificationEnv {}
