/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=fixtures/qualification/wrangler.jsonc --include-runtime=false --env-interface=QualificationEnv fixtures/qualification/worker-configuration.d.ts` (hash: 5b31f121ea342e6b2e7021019581742b)
interface __BaseEnv_QualificationEnv {
  KV: KVNamespace;
  BUCKET: R2Bucket;
  DB: D1Database;
  QUEUE: Queue;
  PROBE: DurableObjectNamespace<import("./worker").Recovery>;
  SERVICE: Service<typeof import("./worker").ServiceProbe>;
  FLOW: Workflow<
    Parameters<import("./worker").RecoveryWorkflow["run"]>[0]["payload"]
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
    durableNamespaces: "Recovery";
  }
  interface Env extends __BaseEnv_QualificationEnv {}
}
interface QualificationEnv extends __BaseEnv_QualificationEnv {}
