/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=fixtures/repro/wrangler.jsonc --include-runtime=false --env-interface=ReproEnv fixtures/repro/worker-configuration.d.ts` (hash: 8d598b2204b8b51702a0a2334e4417c9)
interface __BaseEnv_ReproEnv {
	PROBE: DurableObjectNamespace<import("./worker").Repro>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "Repro";
	}
	interface Env extends __BaseEnv_ReproEnv {}
}
interface ReproEnv extends __BaseEnv_ReproEnv {}
