/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=fixtures/extensions/wrangler.jsonc --include-runtime=false --env-interface=ExtensionEnv fixtures/extensions/worker-configuration.d.ts` (hash: 678e3303b2516789898ed26f13768689)
interface __BaseEnv_ExtensionEnv {
  KV: KVNamespace;
  BUCKET: R2Bucket;
  DB: D1Database;
  QUEUE: Queue;
  LOADER: WorkerLoader;
  ASSETS: Fetcher;
  PROBE: DurableObjectNamespace<import("./worker").Probe>;
  SERVICE: Service<typeof import("./worker").Service>;
  GATEWAY: Service<typeof import("./worker").Gateway>;
  FLOW: Workflow<
    Parameters<import("./worker").TestWorkflow["run"]>[0]["payload"]
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
    durableNamespaces: "Probe";
  }
  interface Env extends __BaseEnv_ExtensionEnv {}
}
interface ExtensionEnv extends __BaseEnv_ExtensionEnv {}
